// <auto-generated />
using System;
using Autotrade.MarketData.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Autotrade.MarketData.Infra.Data.Migrations
{
    [DbContext(typeof(MarketDataContext))]
    [Migration("20260513045119_AddMarketDataTape")]
    partial class AddMarketDataTape
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Autotrade.MarketData.Domain.Entities.ClobTradeTick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExchangeTradeId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal?>("FeeRateBps")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("Size")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("TimestampUnixMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("MarketId", "TokenId", "ExchangeTradeId")
                        .IsUnique()
                        .HasDatabaseName("IX_ClobTradeTicks_Dedup");

                    b.HasIndex("MarketId", "TokenId", "TimestampUnixMilliseconds")
                        .HasDatabaseName("IX_ClobTradeTicks_Market_Token_UnixTime");

                    b.HasIndex("MarketId", "TokenId", "TimestampUtc")
                        .HasDatabaseName("IX_ClobTradeTicks_Market_Token_Time");

                    b.ToTable("ClobTradeTicks", (string)null);
                });

            modelBuilder.Entity("Autotrade.MarketData.Domain.Entities.Market", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MarketId")
                        .IsUnique()
                        .HasDatabaseName("IX_Markets_MarketId_Unique");

                    b.ToTable("Markets", (string)null);
                });

            modelBuilder.Entity("Autotrade.MarketData.Domain.Entities.MarketPriceTick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("Size")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceSequence")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("TimestampUnixMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("MarketId", "TokenId", "TimestampUnixMilliseconds")
                        .HasDatabaseName("IX_MarketPriceTicks_Market_Token_UnixTime");

                    b.HasIndex("MarketId", "TokenId", "TimestampUtc")
                        .HasDatabaseName("IX_MarketPriceTicks_Market_Token_Time");

                    b.HasIndex("MarketId", "TokenId", "SourceName", "SourceSequence")
                        .HasDatabaseName("IX_MarketPriceTicks_Market_Token_Source_Sequence");

                    b.ToTable("MarketPriceTicks", (string)null);
                });

            modelBuilder.Entity("Autotrade.MarketData.Domain.Entities.MarketResolutionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ResolvedUnixMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("MarketId", "ResolvedAtUtc")
                        .HasDatabaseName("IX_MarketResolutionEvents_Market_ResolvedAt");

                    b.HasIndex("MarketId", "ResolvedUnixMilliseconds")
                        .HasDatabaseName("IX_MarketResolutionEvents_Market_ResolvedUnix");

                    b.ToTable("MarketResolutionEvents", (string)null);
                });

            modelBuilder.Entity("Autotrade.MarketData.Domain.Entities.OrderBookDepthSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AsksJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("BidsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("TimestampUnixMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("MarketId", "TokenId", "TimestampUnixMilliseconds")
                        .HasDatabaseName("IX_OrderBookDepthSnapshots_Market_Token_UnixTime");

                    b.HasIndex("MarketId", "TokenId", "TimestampUtc")
                        .HasDatabaseName("IX_OrderBookDepthSnapshots_Market_Token_Time");

                    b.HasIndex("MarketId", "TokenId", "SnapshotHash", "TimestampUtc")
                        .IsUnique()
                        .HasDatabaseName("IX_OrderBookDepthSnapshots_Dedup");

                    b.ToTable("OrderBookDepthSnapshots", (string)null);
                });

            modelBuilder.Entity("Autotrade.MarketData.Domain.Entities.OrderBookTopTick", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BestAskPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal?>("BestAskSize")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<decimal?>("BestBidPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal?>("BestBidSize")
                        .HasPrecision(28, 8)
                        .HasColumnType("numeric(28,8)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceSequence")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal?>("Spread")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<long>("TimestampUnixMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("MarketId", "TokenId", "TimestampUnixMilliseconds")
                        .HasDatabaseName("IX_OrderBookTopTicks_Market_Token_UnixTime");

                    b.HasIndex("MarketId", "TokenId", "TimestampUtc")
                        .HasDatabaseName("IX_OrderBookTopTicks_Market_Token_Time");

                    b.HasIndex("MarketId", "TokenId", "SourceName", "SourceSequence")
                        .HasDatabaseName("IX_OrderBookTopTicks_Market_Token_Source_Sequence");

                    b.ToTable("OrderBookTopTicks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
