// <auto-generated />
using System;
using Autotrade.OpportunityDiscovery.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Autotrade.OpportunityDiscovery.Infra.Data.Migrations
{
    [DbContext(typeof(OpportunityDiscoveryContext))]
    [Migration("20260513140754_OpportunityV2Lifecycle")]
    partial class OpportunityV2Lifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Autotrade.OpportunityDiscovery.Domain.Entities.EvidenceCitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorityKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ClaimJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EvidenceItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EvidenceSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOfficial")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("RelevanceScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceSnapshotId")
                        .HasDatabaseName("IX_OpportunityEvidenceCitations_SnapshotId");

                    b.HasIndex("SourceKey", "ObservedAtUtc")
                        .HasDatabaseName("IX_OpportunityEvidenceCitations_Source_Time");

                    b.ToTable("OpportunityEvidenceCitations", (string)null);
                });

            modelBuilder.Entity("Autotrade.OpportunityDiscovery.Domain.Entities.EvidenceConflict", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BlocksLivePromotion")
                        .HasColumnType("boolean");

                    b.Property<string>("ConflictKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EvidenceSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceKeysJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceSnapshotId")
                        .HasDatabaseName("IX_OpportunityEvidenceConflicts_SnapshotId");

                    b.HasIndex("EvidenceSnapshotId", "Severity")
                        .HasDatabaseName("IX_OpportunityEvidenceConflicts_Snapshot_Severity");

                    b.ToTable("OpportunityEvidenceConflicts", (string)null);
                });

            modelBuilder.Entity("Autotrade.OpportunityDiscovery.Domain.Entities.EvidenceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("SourceQuality")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ResearchRunId")
                        .HasDatabaseName("IX_OpportunityEvidenceItems_RunId");

                    b.HasIndex("ResearchRunId", "ContentHash")
                        .IsUnique()
                        .HasDatabaseName("IX_OpportunityEvidenceItems_RunId_ContentHash");

                    b.ToTable("OpportunityEvidenceItems", (string)null);
                });

            modelBuilder.Entity("Autotrade.OpportunityDiscovery.Domain.Entities.EvidenceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LiveGateReasonsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("LiveGateStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SnapshotAsOfUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("MarketId", "SnapshotAsOfUtc")
                        .HasDatabaseName("IX_OpportunityEvidenceSnapshots_Market_AsOf");

                    b.HasIndex("OpportunityId", "SnapshotAsOfUtc")
                        .HasDatabaseName("IX_OpportunityEvidenceSnapshots_Opportunity_AsOf");

                    b.ToTable("OpportunityEvidenceSnapshots", (string)null);
                });

            modelBuilder.Entity("Autotrade.OpportunityDiscovery.Domain.Entities.ExecutableOpportunityPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Edge")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("EntryMaxPrice")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("EvidenceIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("FairProbability")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<Guid>("HypothesisId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal>("MaxNotional")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("MaxSpread")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<decimal>("StopLossPrice")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("TakeProfitPrice")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HypothesisId")
                        .HasDatabaseName("IX_ExecutableOpportunityPolicies_HypothesisId");

                    b.HasIndex("MarketId", "Status")
                        .HasDatabaseName("IX_ExecutableOpportunityPolicies_Market_Status");

                    b.HasIndex("Status", "ValidUntilUtc")
                        .HasDatabaseName("IX_ExecutableOpportunityPolicies_Status_ValidUntil");

                    b.ToTable("ExecutableOpportunityPolicies", (string)null);
                });

            modelBuilder.Entity("Autotrade.OpportunityDiscovery.Domain.Entities.MarketOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompiledPolicyJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Edge")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("EvidenceIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("FairProbability")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("LlmOutputJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScoreJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ResearchRunId")
                        .HasDatabaseName("IX_MarketOpportunities_RunId");

                    b.HasIndex("MarketId", "Status")
                        .HasDatabaseName("IX_MarketOpportunities_Market_Status");

                    b.HasIndex("Status", "ValidUntilUtc")
                        .HasDatabaseName("IX_MarketOpportunities_Status_ValidUntil");

                    b.ToTable("MarketOpportunities", (string)null);
                });

            modelBuilder.Entity("Autotrade.OpportunityDiscovery.Domain.Entities.OfficialConfirmation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Claim")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("ConfirmationKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EvidenceSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("EvidenceSnapshotId")
                        .HasDatabaseName("IX_OpportunityOfficialConfirmations_SnapshotId");

                    b.HasIndex("SourceKey", "ConfirmedAtUtc")
                        .HasDatabaseName("IX_OpportunityOfficialConfirmations_Source_Time");

                    b.ToTable("OpportunityOfficialConfirmations", (string)null);
                });

            modelBuilder.Entity("Autotrade.OpportunityDiscovery.Domain.Entities.OpportunityEvaluationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("EvaluationKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("HypothesisId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketTapeSliceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ReplaySeed")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("RunVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HypothesisId", "EvaluationKind", "StartedAtUtc")
                        .HasDatabaseName("IX_OpportunityEvaluationRuns_Hypothesis_Kind_Time");

                    b.ToTable("OpportunityEvaluationRuns", (string)null);
                });

            modelBuilder.Entity("Autotrade.OpportunityDiscovery.Domain.Entities.OpportunityFeatureSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EvidenceSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("FeatureVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FeaturesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("HypothesisId")
                        .HasColumnType("uuid");

                    b.Property<string>("MarketTapeSliceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("HypothesisId", "CreatedAtUtc")
                        .HasDatabaseName("IX_OpportunityFeatureSnapshots_Hypothesis_Time");

                    b.ToTable("OpportunityFeatureSnapshots", (string)null);
                });

            modelBuilder.Entity("Autotrade.OpportunityDiscovery.Domain.Entities.OpportunityHypothesis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveLiveAllocationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivePolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("MarketTapeSliceId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReplaySeed")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("ResearchRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScoreVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SourceSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Thesis")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ResearchRunId")
                        .HasDatabaseName("IX_OpportunityHypotheses_RunId");

                    b.HasIndex("MarketId", "Status")
                        .HasDatabaseName("IX_OpportunityHypotheses_Market_Status");

                    b.HasIndex("Status", "UpdatedAtUtc")
                        .HasDatabaseName("IX_OpportunityHypotheses_Status_Time");

                    b.ToTable("OpportunityHypotheses", (string)null);
                });

            modelBuilder.Entity("Autotrade.OpportunityDiscovery.Domain.Entities.OpportunityLifecycleTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EvidenceIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FromStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("HypothesisId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("HypothesisId", "OccurredAtUtc")
                        .HasDatabaseName("IX_OpportunityLifecycleTransitions_Hypothesis_Time");

                    b.ToTable("OpportunityLifecycleTransitions", (string)null);
                });

            modelBuilder.Entity("Autotrade.OpportunityDiscovery.Domain.Entities.OpportunityLiveAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExecutablePolicyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HypothesisId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MaxContracts")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<decimal>("MaxNotional")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExecutablePolicyId")
                        .HasDatabaseName("IX_OpportunityLiveAllocations_PolicyId");

                    b.HasIndex("HypothesisId")
                        .HasDatabaseName("IX_OpportunityLiveAllocations_HypothesisId");

                    b.HasIndex("Status", "ValidUntilUtc")
                        .HasDatabaseName("IX_OpportunityLiveAllocations_Status_ValidUntil");

                    b.ToTable("OpportunityLiveAllocations", (string)null);
                });

            modelBuilder.Entity("Autotrade.OpportunityDiscovery.Domain.Entities.OpportunityPromotionGate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EvaluatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Evaluator")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("EvidenceIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("GateKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("HypothesisId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("HypothesisId", "GateKind", "EvaluatedAtUtc")
                        .HasDatabaseName("IX_OpportunityPromotionGates_Hypothesis_Kind_Time");

                    b.ToTable("OpportunityPromotionGates", (string)null);
                });

            modelBuilder.Entity("Autotrade.OpportunityDiscovery.Domain.Entities.OpportunityReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId")
                        .HasDatabaseName("IX_OpportunityReviews_OpportunityId");

                    b.ToTable("OpportunityReviews", (string)null);
                });

            modelBuilder.Entity("Autotrade.OpportunityDiscovery.Domain.Entities.OpportunityScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CalibrationBucket")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ComponentsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Edge")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("FairProbability")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<Guid>("FeatureSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HypothesisId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScoreVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("HypothesisId", "CreatedAtUtc")
                        .HasDatabaseName("IX_OpportunityScores_Hypothesis_Time");

                    b.ToTable("OpportunityScores", (string)null);
                });

            modelBuilder.Entity("Autotrade.OpportunityDiscovery.Domain.Entities.ResearchRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("EvidenceCount")
                        .HasColumnType("integer");

                    b.Property<string>("MarketUniverseJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("OpportunityCount")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_OpportunityResearchRuns_Status_Time");

                    b.ToTable("OpportunityResearchRuns", (string)null);
                });

            modelBuilder.Entity("Autotrade.OpportunityDiscovery.Domain.Entities.SourceObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EvidenceSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ObservationJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ObservationKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OpportunityId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("SourceProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId")
                        .HasDatabaseName("IX_OpportunitySourceObservations_OpportunityId");

                    b.HasIndex("SourceKey", "ObservedAtUtc")
                        .HasDatabaseName("IX_OpportunitySourceObservations_Source_Time");

                    b.ToTable("OpportunitySourceObservations", (string)null);
                });

            modelBuilder.Entity("Autotrade.OpportunityDiscovery.Domain.Entities.SourceProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorityKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("CoveredCategoriesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExpectedLatencySeconds")
                        .HasColumnType("integer");

                    b.Property<decimal>("HistoricalConflictRate")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<decimal>("HistoricalPassedGateContribution")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<bool>("IsOfficial")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ReliabilityScore")
                        .HasPrecision(8, 4)
                        .HasColumnType("numeric(8,4)");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("SupersedesProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceKey")
                        .HasDatabaseName("IX_OpportunitySourceProfiles_SourceKey");

                    b.HasIndex("SourceKey", "Version")
                        .IsUnique()
                        .HasDatabaseName("IX_OpportunitySourceProfiles_SourceKey_Version");

                    b.ToTable("OpportunitySourceProfiles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
