// <auto-generated />
using System;
using Autotrade.Trading.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Autotrade.Trading.Infra.Data.Migrations
{
    [DbContext(typeof(TradingContext))]
    partial class TradingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Autotrade.Trading.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientOrderId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExchangeOrderId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset?>("GoodTilDateUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("NegRisk")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("OrderSalt")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OrderTimestamp")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("bytea");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StrategyId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TimeInForce")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TokenId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TradingAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId")
                        .HasDatabaseName("IX_Orders_ClientOrderId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_Orders_CorrelationId");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_Orders_CreatedAtUtc");

                    b.HasIndex("ExchangeOrderId")
                        .IsUnique()
                        .HasDatabaseName("UX_Orders_ExchangeOrderId")
                        .HasFilter("\"ExchangeOrderId\" IS NOT NULL");

                    b.HasIndex("MarketId")
                        .HasDatabaseName("IX_Orders_MarketId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Orders_Status");

                    b.HasIndex("StrategyId")
                        .HasDatabaseName("IX_Orders_StrategyId");

                    b.HasIndex("TradingAccountId", "Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_Orders_Aggregate_Status_Time");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Autotrade.Trading.Domain.Entities.OrderEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ContextJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RunSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId")
                        .HasDatabaseName("IX_OrderEvents_ClientOrderId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_OrderEvents_CorrelationId");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_OrderEvents_CreatedAtUtc");

                    b.HasIndex("MarketId")
                        .HasDatabaseName("IX_OrderEvents_MarketId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_OrderEvents_OrderId");

                    b.HasIndex("RunSessionId")
                        .HasDatabaseName("IX_OrderEvents_RunSessionId");

                    b.HasIndex("StrategyId")
                        .HasDatabaseName("IX_OrderEvents_StrategyId");

                    b.HasIndex("OrderId", "CreatedAtUtc")
                        .HasDatabaseName("IX_OrderEvents_Order_Time");

                    b.ToTable("OrderEvents", (string)null);
                });

            modelBuilder.Entity("Autotrade.Trading.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("RealizedPnl")
                        .HasColumnType("numeric(18,10)");

                    b.Property<Guid>("TradingAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TradingAccountId", "MarketId", "Outcome")
                        .IsUnique()
                        .HasDatabaseName("UX_Positions_Aggregate_Market_Outcome");

                    b.ToTable("Positions", (string)null);
                });

            modelBuilder.Entity("Autotrade.Trading.Domain.Entities.RiskEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TradingAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TradingAccountId", "Severity", "CreatedAtUtc")
                        .HasDatabaseName("IX_RiskEvents_Aggregate_Severity_Time");

                    b.ToTable("RiskEvents", (string)null);
                });

            modelBuilder.Entity("Autotrade.Trading.Domain.Entities.RiskEventLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ContextJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MarketId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StrategyId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Code", "CreatedAtUtc")
                        .HasDatabaseName("IX_RiskEventLogs_Code_Time");

                    b.HasIndex("Severity", "CreatedAtUtc")
                        .HasDatabaseName("IX_RiskEventLogs_Severity_Time");

                    b.HasIndex("StrategyId", "CreatedAtUtc")
                        .HasDatabaseName("IX_RiskEventLogs_Strategy_Time");

                    b.ToTable("RiskEventLogs", (string)null);
                });

            modelBuilder.Entity("Autotrade.Trading.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientOrderId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExchangeTradeId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("numeric(18,10)");

                    b.Property<string>("MarketId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StrategyId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TradingAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClientOrderId")
                        .HasDatabaseName("IX_Trades_ClientOrderId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_Trades_CorrelationId");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_Trades_CreatedAtUtc");

                    b.HasIndex("ExchangeTradeId")
                        .IsUnique()
                        .HasDatabaseName("UX_Trades_ExchangeTradeId");

                    b.HasIndex("MarketId")
                        .HasDatabaseName("IX_Trades_MarketId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("IX_Trades_OrderId");

                    b.HasIndex("StrategyId")
                        .HasDatabaseName("IX_Trades_StrategyId");

                    b.HasIndex("TradingAccountId")
                        .HasDatabaseName("IX_Trades_TradingAccountId");

                    b.HasIndex("MarketId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Trades_Market_Time");

                    b.HasIndex("StrategyId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Trades_Strategy_Time");

                    b.ToTable("Trades", (string)null);
                });

            modelBuilder.Entity("Autotrade.Trading.Domain.Entities.TradingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AccountUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("AccountUpdatedAtUtc");

                    b.Property<decimal>("AvailableCapital")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("AvailableCapital");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("bytea");

                    b.Property<decimal>("TotalCapital")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("TotalCapital");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WalletAddress")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("WalletAddress");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .HasDatabaseName("IX_TradingAccounts_Id");

                    b.HasIndex("WalletAddress")
                        .IsUnique()
                        .HasDatabaseName("UX_TradingAccounts_WalletAddress");

                    b.ToTable("TradingAccounts", (string)null);
                });

            modelBuilder.Entity("Autotrade.Trading.Domain.Entities.Order", b =>
                {
                    b.HasOne("Autotrade.Trading.Domain.Entities.TradingAccount", null)
                        .WithMany("Orders")
                        .HasForeignKey("TradingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Autotrade.Trading.Domain.Shared.ValueObjects.Quantity", "FilledQuantity", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18,10)")
                                .HasColumnName("FilledQuantity");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("Autotrade.Trading.Domain.Shared.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18,10)")
                                .HasColumnName("Price");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("Autotrade.Trading.Domain.Shared.ValueObjects.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18,10)")
                                .HasColumnName("Quantity");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("FilledQuantity")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("Autotrade.Trading.Domain.Entities.Position", b =>
                {
                    b.HasOne("Autotrade.Trading.Domain.Entities.TradingAccount", null)
                        .WithMany("Positions")
                        .HasForeignKey("TradingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Autotrade.Trading.Domain.Shared.ValueObjects.Price", "AverageCost", b1 =>
                        {
                            b1.Property<Guid>("PositionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18,10)")
                                .HasColumnName("AverageCost");

                            b1.HasKey("PositionId");

                            b1.ToTable("Positions");

                            b1.WithOwner()
                                .HasForeignKey("PositionId");
                        });

                    b.OwnsOne("Autotrade.Trading.Domain.Shared.ValueObjects.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("PositionId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18,10)")
                                .HasColumnName("Quantity");

                            b1.HasKey("PositionId");

                            b1.ToTable("Positions");

                            b1.WithOwner()
                                .HasForeignKey("PositionId");
                        });

                    b.Navigation("AverageCost")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("Autotrade.Trading.Domain.Entities.RiskEvent", b =>
                {
                    b.HasOne("Autotrade.Trading.Domain.Entities.TradingAccount", null)
                        .WithMany("RiskEvents")
                        .HasForeignKey("TradingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Autotrade.Trading.Domain.Entities.Trade", b =>
                {
                    b.HasOne("Autotrade.Trading.Domain.Entities.TradingAccount", null)
                        .WithMany("Trades")
                        .HasForeignKey("TradingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Autotrade.Trading.Domain.Shared.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("TradeId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18,10)")
                                .HasColumnName("Price");

                            b1.HasKey("TradeId");

                            b1.ToTable("Trades");

                            b1.WithOwner()
                                .HasForeignKey("TradeId");
                        });

                    b.OwnsOne("Autotrade.Trading.Domain.Shared.ValueObjects.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("TradeId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric(18,10)")
                                .HasColumnName("Quantity");

                            b1.HasKey("TradeId");

                            b1.ToTable("Trades");

                            b1.WithOwner()
                                .HasForeignKey("TradeId");
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("Autotrade.Trading.Domain.Entities.TradingAccount", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Positions");

                    b.Navigation("RiskEvents");

                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
